### ISSUE TITLE
CSS bug

### ISSUE THREAD

**Issue by abcdw** [rednotes/rednotes.github.io#21]
![checkers-post](https://cloud.githubusercontent.com/assets/1218615/9189644/1585a496-3ff4-11e5-87b0-172277d56f42.jpg)

**Comment by Frodox** [comment]
iPhone only, или повсеместно?

**Comment by abcdw** [comment]
Повсеместно, из-за embeded youtube.

вс, 16 авг. 2015, 15:41, Vit Ry <notifications@github.com>:
